### PR TITLE
fix(cli): set restrictive file permissions on tokens.json

### LINKED ISSUE #32: CLI: tokens.json written without restrictive file permissions (missing mode 0o600)
## Summary

`token-store.ts` writes `~/.a2x/tokens.json` without setting file permissions, while `config.ts` correctly uses `mode: 0o600`. Since `tokens.json` stores sensitive credentials (Bearer tokens, API keys, OAuth2 access tokens), other users on a shared system can read the file.

## Root cause

`packages/cli/src/token-store.ts` line 33:

```typescript
// token-store.ts — no mode set, uses system default umask (typically 0o644)
fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), 'utf-8');
```

vs `packages/cli/src/config.ts` lines 44-47:

```typescript
// config.ts — correctly restricted to owner-only
fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), {
  encoding: 'utf-8',
  mode: 0o600,
});
```

## Impact

On shared systems (CI runners, multi-user Linux servers), other system users can read `~/.a2x/tokens.json` and extract stored credentials. The default umask (`0o022`) results in file permissions `0o644` (world-readable).

`config.json` contains non-sensitive settings (registry URL), while `tokens.json` contains actual secrets — so the more sensitive file is the one missing protection.

## Suggested fix

```typescript
function writeStore(data: StoreData): void {
  fs.mkdirSync(STORE_DIR, { recursive: true });
  fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), {
    encoding: 'utf-8',
    mode: 0o600,
  });
}
```

### PR DESCRIPTION
**Pull request by shkangr**
## Summary

Closes #32

`writeStore()` in `token-store.ts` was writing `~/.a2x/tokens.json` without setting file permissions, defaulting to umask (typically `0o644`, world-readable). This exposes stored credentials to other users on shared systems.

### Fix

Add `mode: 0o600` (owner read/write only), matching the pattern already used by `config.ts`.

```diff
- fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), 'utf-8');
+ fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), {
+   encoding: 'utf-8',
+   mode: 0o600,
+ });
```

## Test plan

- [x] Lint passes
- [x] Build passes

### CODE REVIEW

File: packages/cli/src/token-store.ts [hunk 1]
```diff
@@ -30,7 +30,10 @@ function readStore(): StoreData {
 
 function writeStore(data: StoreData): void {
   fs.mkdirSync(STORE_DIR, { recursive: true });
-  fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), 'utf-8');
+  fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), {
+    encoding: 'utf-8',
+    mode: 0o600,
+  });
```
Comment (ost006) [inline packages/cli/src/token-store.ts]: `fs.writeFileSync`'s `mode` option only applies when the target file is **newly created**. For users who already have `~/.a2x/tokens.json` from a previous version, the file stays at whatever umask default it was originally created with (commonly `0o644`) — this fix won't retroactively tighten those files.

Reproduced locally:

```js
fs.writeFileSync('/tmp/x', 'v1', { mode: 0o644 }); // stat → 0o644
fs.writeFileSync('/tmp/x', 'v2', { mode: 0o600 }); // stat → still 0o644
```

Adding an explicit `chmodSync` after the write closes the gap and also lets us tighten the parent directory:

```suggestion
  fs.mkdirSync(STORE_DIR, { recursive: true, mode: 0o700 });
  fs.writeFileSync(STORE_PATH, JSON.stringify(data, null, 2), {
    encoding: 'utf-8',
    mode: 0o600,
  });
  fs.chmodSync(STORE_PATH, 0o600);
```

`chmodSync` is a single, idempotent syscall, and `writeStore` is only called on login/logout so there's no hot-path concern. The same limitation exists in `config.ts`, but since `config.json` is non-sensitive it can be addressed separately.

**Review by ost006 — COMMENTED** [review]
Nice catch on the umask default — one follow-up on the scope of the fix. See inline suggestion.

File: packages/cli/src/token-store.ts (hunk 1 above)
Comment (shkangr) [reply packages/cli/src/token-store.ts]: Fixed.
commit : 952dc17261d2b2ce4a9f9e55710395456a3eacff
